spring:
  profiles:
    active: dev
    ##默认密码为空
  redis:
    #主机ip
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        min-idle: 0
          # 最大空闲连接
        max-idle: 8
          # 最大活跃连接
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库
    database: 15